services:
  omni:
    build: .
    image: omni
    volumes:
      - ./input/:/input
      - ./output/:/output
      - ./main.py:/main.py
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["0"]
            capabilities: [gpu]
